# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-23 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LieuArrivee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localite', models.CharField(db_index=True, max_length=20)),
                ('quartier', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LieuDapart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localite', models.CharField(db_index=True, max_length=20)),
                ('quartier', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('heure_depart', models.DateTimeField()),
                ('nbPlace_Reservee', models.IntegerField(default=0)),
                ('non_client', models.CharField(max_length=20)),
                ('contact_client', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajet_creation_date', models.DateField(auto_now_add=True)),
                ('date_depart', models.DateField()),
                ('heure_depart', models.DateTimeField()),
                ('date_arrivee', models.DateField()),
                ('heure_arrivee', models.DateTimeField()),
                ('tarif', models.CharField(max_length=8)),
                ('commentaire', models.TextField(blank=True, help_text='Decrire les eventuels detours')),
                ('arrivee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blablaCar.LieuArrivee')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blablaCar.LieuDapart')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_conducteur', models.CharField(blank=True, max_length=30)),
                ('numero_conducteur1', models.CharField(max_length=15)),
                ('numero_conducteur2', models.CharField(blank=True, max_length=15)),
                ('numero_vehicule', models.CharField(db_index=True, max_length=10)),
                ('nbPlace', models.IntegerField(default=0)),
                ('marque', models.CharField(blank=True, choices=[('toy', 'TOYOTA'), ('mer', 'MERCEDEZ BENZ'), ('hun', 'HUNDAI'), ('hon', 'HONDA'), ('ren', 'RENAULT'), ('peu', 'PEUGEAUT'), ('oth', 'AUTRE')], default='toy', help_text='Si Autre svp specifier une image', max_length=3)),
                ('image_vehicule', models.ImageField(blank=True, upload_to='blablaCar/images/')),
            ],
        ),
        migrations.AddField(
            model_name='trajet',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blablaCar.Vehicule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trajet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blablaCar.Trajet'),
        ),
    ]
