# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_depart',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='heure_depart',
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_client1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nbPlace_Reservee',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='non_client',
            field=models.CharField(max_length=30),
        ),
    ]
