# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0002_auto_20200203_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='non_client',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
