# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0004_auto_20200204_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='heure_arrivee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='heure_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
