# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0005_auto_20200207_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='heure_arrivee',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='heure_depart',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
