# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0006_auto_20200207_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='idTrajet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
