# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0007_reservation_idtrajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
