# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-08 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0008_trajet_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='numero_vehicule',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
