# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0010_auto_20200210_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, choices=[('TOYOTA', 'TOYOTA'), ('MERCEDEZ-BENZ', 'MERCEDEZ-BENZ'), ('HUNDAI', 'HUNDAI'), ('HONDA', 'HONDA'), ('RENAULT', 'RENAULT'), ('PEUGEAUT', 'PEUGEAUT'), ('AUTRE', 'AUTRE')], default='toy', help_text='Si Autre svp specifier une image', max_length=15),
        ),
    ]
