# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-11 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0012_auto_20200212_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieuarrivee',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='lieudapart',
            name='quartier',
        ),
    ]
