# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0013_auto_20200212_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='NousContactez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('addresse', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Autres commentaires')),
            ],
        ),
    ]
