# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-14 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0014_nouscontactez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='date_arrivee',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='date_depart',
        ),
    ]
