# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-13 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0016_reservation_pseudo_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 12, 21, 3, 769859, tzinfo=utc)),
        ),
    ]
