# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0017_reservation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
