# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0018_auto_20200413_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
