# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-16 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0019_auto_20200413_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'permissions': (('can_change_img_vehicule', 'Can change img vehicule'),)},
        ),
    ]
