# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0020_auto_20200416_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blablaCar.LieuArrivee'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blablaCar.LieuDapart'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blablaCar.Vehicule'),
        ),
    ]
