# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-07 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0023_auto_20200507_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': (('can_see_trajet_booked', 'can_supp_trajet_booked'),)},
        ),
    ]
