# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-07 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0024_auto_20200507_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_view_all_trajet_booked', 'Can view all trajet booked')]},
        ),
    ]
