# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0028_auto_20200525_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
