# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0030_auto_20200526_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact_client',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nbPlace_Reservee',
            field=models.IntegerField(default=0),
        ),
    ]
