# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blablaCar', '0031_auto_20200526_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_vehicule',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
